log:
  disable_sentry: true
  level: debug

db:
  url: "postgres://postgres:postgres@localhost:5432/evm_saver?sslmode=disable"

listener:
  addr: :8000

evm:
  contract_addr: ""
  rpc: ""
  start_from_block:
  network_name:
  block_window:

broadcaster:
  addr: ""
  sender_account: ""

core:
  addr:

cosmos:
  addr:

subscriber:
  min_retry_period:
  max_retry_period:

profiler:
  enabled: true
  addr: :8080

state_contract_cfg:
  issuer_id: ['', '']
  disable_filtration: true
  states_per_request: 15
  max_blocks_per_request: 100